In [1]:
import numpy as np

10.9.20

In [2]:
#Función para ejemplos
def g(x0):
    return sum(x0**2+2*x0-5)

x0 = np.array([4,2,5,2])

### Gradiente

In [3]:
def grad(f, x0):
    n = x0.size
    eps = 0.00001
    res = np.zeros(n)
    for i in range(n):
        aux = np.zeros(n)
        aux[i] = eps
        x1 = x0 + aux
        res[i] = (f(x1) - f(x0))/eps        
    return res

In [4]:
grad(g,x0)

array([10.00001,  6.00001, 12.00001,  6.00001])

### Hessiana
En hess1 intenté hacer lo del siguiente link, pero no me quedaba: http://www2.math.umd.edu/~dlevy/classes/amsc466/lecture-notes/differentiation-chap.pdf.

En hess, usé diferenciación como en: https://neos-guide.org/content/difference-approximations#:~:text=One%20method%20for%20approximating%20the,evaluated%20at%20two%20nearby%20points.

In [5]:
def hess1(f,x0):
    n = x0.size
    eps = 0.00001
    res = np.zeros([n,n])
    for i in range(n):
        for j in range(i+1): #porque es simétrica, y entonces mejor res[j][i] = res[i][j]
            aux1 = np.zeros(n)
            aux2 = np.zeros(n)
            #aux1 = aux2 no jala en numpy; mejor np.copy
            aux1[i] = eps
            aux2[j] = eps
            xij = x0 + aux1 + aux2
            xi = x0 + aux1
            xj = x0 + aux2
            res[i][j] = (f(xij) - f(xi) - f(xj) + f(x0))/(eps**2)
            res[j][i] = res[i][j]
    return res

In [6]:
hess1(g,x0)

array([[2.00010675e+00, 7.10542736e-05, 0.00000000e+00, 0.00000000e+00],
       [7.10542736e-05, 2.00003569e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.99996464e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00003569e+00]])

In [7]:
def hess(f,x0):
    n = x0.size
    eps = 0.00001
    res = np.zeros((n,n))
    for i in range(n):
        aux = np.zeros(n)
        aux[i] = eps
        x1 = x0 + aux
        res[:,i] = (grad(f,x1)-grad(f,x0))/eps
    return res

In [8]:
hess(g,x0)

array([[2.00010675e+00, 7.10542736e-05, 0.00000000e+00, 0.00000000e+00],
       [7.10542736e-05, 2.00003569e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.99996464e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00003569e+00]])

### Condiciones de optimalidad
Queremos checar los second orden necessary conditions, es decir,

$∇f(x^*) = 0$

$∇^2f(x^*)$ semidefinida positiva (para esto, lo más fácil es usar los eigenvalores)

In [9]:
def condiciones_optimalidad(f,x0):
    res = ""
    if np.all(grad(f,x0) == 0):
        res += "Cumple con tener gradiente 0. "
    else:
        res += "No cumple con tener gradiente 0. "
    
    eigs = np.linalg.eigvals(hess(f,x0))
    if np.all(eigs > 0):
        res += "Cumple con tener Hessiana semidefinida."
    else:
        res += "No cumple con tener Hessiana semidefinida."
        
    return res

In [10]:
condiciones_optimalidad(g,x0)

'No cumple con tener gradiente 0. Cumple con tener Hessiana semidefinida.'

### Función de aproximación

In [11]:
def mk (f,x0,p):
    H = hess(f,x0)
    G = grad(f,x0)
    aux = np.dot(p.T,H)
    return f(x0) + np.dot(p.T,G) + 0.5*np.dot(aux,p)

### Ejemplo

In [12]:
print(grad(g,x0))
print(hess(g,x0))
p = np.array([1,2,3,4])
p = p.T
print(condiciones_optimalidad(g,x0))
print(mk(g,x0,p))

[10.00001  6.00001 12.00001  6.00001]
[[2.00010675e+00 7.10542736e-05 0.00000000e+00 0.00000000e+00]
 [7.10542736e-05 2.00003569e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.99996464e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00003569e+00]]
No cumple con tener gradiente 0. Cumple con tener Hessiana semidefinida.
167.00049327868555
