In [37]:
import numpy as np
from numpy import linalg as LA
import random as ran

In [38]:
def Rosenbrock(x0):
        a=1
        b=100
        x=x0[0]
        y=x0[1]
        f = (a-x)**2 + b*(y-x**2)**2
        return f

In [39]:
def grad(f, x0, h):
    n = len(x0)
    G = np.zeros(n)
    for i in range(n):
        z = np.zeros(n)
        z[i] += h
        xi = x0 + z
        G[i] = (f(xi) - f(x0))/h
    return G

In [40]:
def hess(f,x0,h):
    n = len(x0)
    s= (n,n)
    H = np.zeros(s)
    for i in range(n):
        for j in range(n):
            z1 = np.zeros(n)
            z2 = z1
            z1[i] += h
            z2[j] += h
            x1 = x0 + z1 + z2
            x2 = x0 + z1 - z2
            x3 = x0 - z1 + z2
            x4 = x0 - z1 - z2
            H[i,j] = (f(x1) - f(x2) - f(x3) + f(x4))/(4*(h**2))
    return H

In [41]:
def defpos(f,x0,h):
    Con = LA.eig(hess(f,x0,h))
    CO = np.all(Con[0] >= h)    
    return CO

In [42]:
def mk(f,x0,h):
    G = grad(f, x0, h)
    H = hess(f, x0, h)
    norma = np.linalg.norm(G)
    p1 = -G/norma
    p = np.transpose(p1)
    mk = f(x0) + p*G + 0.5*p*H*p1
    return mk

In [43]:
def BLS(a,f,xk,pk,h):         ##  Algoritmo 3.1: Backtracking Line Search
    rho=ran.uniform(0,1)
    c=ran.uniform(0,1)
    a0=a
    while f(xk +a0*pk) > f(xk) + c*a0*np.dot(np.transpose(grad(f,xk,h)),pk):
        a0 = rho*a0
    return a0

In [44]:
def cholesky2(Bk,h,maxIt=10000):      ##  Algoritmo 3.3: Cholesky with added multiple of the identity.  
    beta=10**-3
    if min(np.diag(Bk)) > 0 :           ##  La utilizamos para obtener Ek del algoritmo 3.2
        t = 0
    else:
        t = -min(np.diag(Bk)) + beta
    for i in range(maxIt):
        try:
            L = LA.cholesky(Bk + t*np.identity(len(Bk)))
            break
        except:
            t = max(2*t,beta)
    return np.dot(L,L)

In [45]:
def NewMod(f,xk,h,maxIt=1000):          ##  Algoritmo 3.2: Line search Newton with modification
    for k in range(maxIt):
         Bk = hess(f,xk,h)
         try:
            L = la.cholesky(Bk)
         except:
            Bk = cholesky2(Bk,h)
            pk = LA.inv(Bk).dot(-grad(f,xk,h))
            a = BLS(1,f,xk,pk,h)
            xk = xk + a*pk
    return xk


In [46]:
x0 = (1.2,1.2)                           ### Prueba del algoritmo 
print("El gradiente es:")
print(grad(Rosenbrock,x0,0.00001))
print("El hessiano es:")
print(hess(Rosenbrock,x0,0.00001))
if(defpos(Rosenbrock,x0,0.00001)):
    print("Bk es definida positiva")
else:
    print("Bk NO es definida positiva")
print("El resultado obtenido con la busqueda lineal de Newton fue:")
print(NewMod(Rosenbrock,x0,0.000001))

El gradiente es:
[115.60625005 -47.999     ]
El hessiano es:
[[5000.00000292  489.99998281]
 [ 489.99998281  799.99999958]]
Bk es definida positiva
El resultado obtenido con la busqueda lineal de Newton fue:
[1.12817739 1.27309686]


In [47]:
def Rosenbrock(x0):                      ## Cambiamos los parámetros de la función de Rosenbrock 
        a=1
        b=50
        x=x0[0]
        y=x0[1]
        f = (a-x)**2 + b*(y-x**2)**2
        return f

In [48]:
x0 = (1.2,1.2)                           ### Segunda prueba del algoritmo 
print("El gradiente es:")
print(grad(Rosenbrock,x0,0.00001))
print("El hessiano es:")
print(hess(Rosenbrock,x0,0.00001))
if(defpos(Rosenbrock,x0,0.00001)):
    print("Bk es definida positiva")
else:
    print("Bk NO es definida positiva")
print("El resultado obtenido con la busqueda lineal de Newton fue:")
print(NewMod(Rosenbrock,x0,0.000001))

El gradiente es:
[ 58.00313002 -23.9995    ]
El hessiano es:
[[2504.00000179  245.99999038]
 [ 245.99999038  399.99999979]]
Bk es definida positiva
El resultado obtenido con la busqueda lineal de Newton fue:
[1.10225776 1.21548061]


In [49]:
def Rosenbrock(x0):                      ## Cambiamos los parámetros de la función de Rosenbrock 
        a=0
        b=100
        x=x0[0]
        y=x0[1]
        f = (a-x)**2 + b*(y-x**2)**2
        return f

In [50]:
x0 = (1.2,1.2)                           ### Tercera prueba del algoritmo 
print("El gradiente es:")
print(grad(Rosenbrock,x0,0.00001))
print("El hessiano es:")
print(hess(Rosenbrock,x0,0.00001))
if(defpos(Rosenbrock,x0,0.00001)):
    print("Bk es definida positiva")
else:
    print("Bk NO es definida positiva")
print("El resultado obtenido con la busqueda lineal de Newton fue:")
print(NewMod(Rosenbrock,x0,0.000001))

El gradiente es:
[117.60625005 -47.999     ]
El hessiano es:
[[5000.00000736  489.99998281]
 [ 489.99998281  800.00000402]]
Bk es definida positiva
El resultado obtenido con la busqueda lineal de Newton fue:
[0.87755503 0.7727446 ]
