# Tour de Python

En este Notebook escribo una guía intuitiva e interactiva de como funciona Python en Jupyter.

holi

## Operaciones básicas

### ayuda

In [2]:
bool?

### declaración de variables

In [3]:
x,y = 3,4.1

### imprimir

In [4]:
print ("el valor de x es",x)
print ("el valor de y es")
y

el valor de x es 3
el valor de y es


4.1

### suma

In [5]:
x + y

7.1

### resta

In [6]:
x-y

-1.0999999999999996

### multiplicación

In [7]:
x*y

12.299999999999999

### división

In [8]:
x/y

0.7317073170731708

### potencias

In [9]:
x**y

90.40597709674623

### modulo (natural y real)

In [10]:
x%y

3.0

### numeros complejos

In [11]:
z = 2 + 3j
z

(2+3j)

### transformar un numero a texto

In [12]:
str(2.3)

'2.3'

### concatenación de texto

In [13]:
"hola," + " te quiero " + str(1000)

'hola, te quiero 1000'

In [14]:
3 * "hola "

'hola hola hola '

### funciones recursivas

In [15]:
x = 1
print (x)

1


In [2]:
x += 1 
print (x)

2


In [3]:
x /= 2
print (x)

1.0


In [4]:
x *= 2
print (x)

2.0


In [5]:
x %= 1.5
print (x)

0.5


### logicos

In [6]:
3 == 3

True

In [7]:
3 != 3

False

In [8]:
3 < 0 or 0 < 3

True

In [17]:
3 < 0 and 3 > 0 

False

### condicional if

In [19]:
x = 1
if x > 3:
    print ("x mayor a 3")
elif x == 3: 
    print ("x igual a 3")
else:
    print ("x menor a 3")

x menor a 3


### Condicional while

In [17]:
x = 0
while x < 10:
    x = x+1
    break
print(x)

1


# Tipos de elementos

In [32]:
type(False)

bool

In [34]:
type(1)

int

In [37]:
type(0.3)

float

In [47]:
type(1+1j)

complex

In [52]:
type('hola')

str

### listas: conjunto ordenado de elementos

In [175]:
x = [1,2,3,4,5]
type(x)

list

In [176]:
x[0]

1

In [177]:
x[1:4]

[2, 3, 4]

In [178]:
x[-1]

5

In [179]:
x.append(6)
x[5]

6

In [180]:
x.pop(0)
x

[2, 3, 4, 5, 6]

In [182]:
x.remove(6)
x

ValueError: list.remove(x): x not in list

In [184]:
empty = []
print (empty)

[]


### tuplas: estructura de elementos no modificable

In [61]:
x = (1,2)
type(x)

tuple

In [62]:
x[0] = 1

TypeError: 'tuple' object does not support item assignment

###  conjuntos

In [45]:
x = {1,2}
type(x)

set

### diccionarios: parejas de elementos con la forma "llave:elemento"

In [18]:
x = {1:'a',2:'b'}
type(x)

dict

In [19]:
x.keys()

dict_keys([1, 2])

In [20]:
x.values()

dict_values(['a', 'b'])

In [21]:
x.items()

dict_items([(1, 'a'), (2, 'b')])

In [22]:
x[1]

'a'

In [23]:
x[3]='c'
x[4]='d'
print(x)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [24]:
del x[3]
x.pop(4)
print(x)

{1: 'a', 2: 'b'}


### for lógico

In [25]:
for x in [1,2,3]:
    print (x)

1
2
3


### Rango: naturales ordenados

In [26]:
for x in range(2):
    print (x)

0
1


In [27]:
for x in range(-2,2):
    print (x)

-2
-1
0
1


In [28]:
for x in range(-6,5,2):
    print(x)

-6
-4
-2
0
2
4


# Funciones

In [29]:
from math import sqrt, atan, acos, pi
def car_esf(x,y,z):
    """
    Esta funcion transforma coordenadas cartesianas en R3 a coordenadas esféricas.
        entrada: x,y,z coordenada cartesiana en R3.
        salida: a1,a2,r coordenada esférica en R3.
    a1 es el angulo horizontal, a2 es el aúngulo vertical, r es el radio.
    """
    if x != 0:
        a1 = atan(y/x)
    else:
        a1 = pi/2
    r = sqrt(x*x + y*y + z*z)
    if r != 0:
        a2 = acos(z/r)
    else:
        a1 = 0
        a2 = 0
    return a1,a2,r

In [30]:
car_esf?

In [31]:
car_esf??

In [32]:
car_esf(1,2,3)

(1.1071487177940904, 0.6405223126794245, 3.7416573867739413)

### Python Interactivo

In [33]:
from ipywidgets import interact

In [34]:
interact(car_esf, x=10, y = 10, z = 10)

interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), IntSlider(value=10, description='…

<function __main__.car_esf(x, y, z)>

# Numpy

Numpy es una librería de python para computación cientifica. En otras palablas, mates mamalonas

In [35]:
import numpy as np #el 'as' nos da un shortcut de la libreria.  

### Arrays

Archivos característicos de Numpy, toman el papel de vectores. son como listas pero con menos propiedades y, por lo tanto, más rapidas

In [53]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [65]:
x[0:2]

array([1, 2])

In [69]:
y = np.arange(3,8)
y

array([3, 4, 5, 6, 7])

In [76]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [94]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
z =np.zeros((2,2,2)) #genera un cubo de ceros
z

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [100]:
a = np.linspace(0,1,11)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [103]:
b = np.ones(3)
b

array([1., 1., 1.])

In [106]:
c = np.empty((2,2)) #no es cero, pero sus entradas son menores al epsilon de maquina
c

array([[4.66211586e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [109]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### tipo de dato

In [48]:
x.dtype

dtype('int64')

esto quiere decir que x es un dato de numpy del tipo entero (int) guardado en 64 bits.

In [113]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [139]:
z = z.astype(int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [141]:
z.ndim #dimension

2

In [142]:
z.shape #tamaño de cada eje de la matriz

(3, 3)

In [123]:
z = np.ones((3,3)).astype(np.int32)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [124]:
z.ndim

2

Notemos que cada Array solo puede contener un solo tipo de datos

### Redimensionar

en numpy podemos transformar vectores en matrices y viceversa de una forma ordenada 

In [131]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [133]:
a = a.reshape((2,2)) #transforma el vector en una matriz de 2 x 2
a

array([[0, 1],
       [2, 3]])

In [137]:
a = a. reshape(4) #lo vuelve a hacer en un vector de 1 x 4 
a

array([0, 1, 2, 3])

In [145]:
b = np.arange(8) #veamos otro ejemplo
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [148]:
b = b.reshape((2,2,2)) #ahora vuelve el vector en una matriz
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [151]:
b = b.ravel() # ravel es otra forma de aplanar una matriz en un vector ordenadamente
b

array([0, 1, 2, 3, 4, 5, 6, 7])