In [2]:
import numpy as np
import sys

In [3]:
def check_optimality(grad, hess): 
    if(np.all(abs(grad) <= eps)):
        try:
            np.linalg.cholesky(hess)
        except np.linalg.LinAlgError as err:
            return False
        return True
    return False

In [4]:
def grad(f, x0):
    size = len(x0)
    gradient = np.zeros(size)
    for i in range(size):
        xi = np.zeros(size) + x0
        xi[i] += eps
        gradient[i] = (f(xi) - f(x0)) / eps
    return gradient

In [5]:
def hess(f, x0): #
    size = len(x0)
    hessian = np.zeros((size, size))
    for i in range(size):
        dxi = np.zeros(size) + x0
        dxi[i]+=eps
        for j in range(size):
            hess = (grad(f, dxi)[j] - grad(f, x0)[j]) / eps
            hessian[i, j] = hess
    return hessian

In [6]:
def f(x0):
    return np.sqrt(sum(x0**2))

In [7]:
def f(x0):
    return x0.item(0)**4 - 2 * x0.item(1) ** 2 + x0.item(2) * x0.item(3)

In [8]:
#Variables globales
x0 = np.array([4, 2, 5, 2])
x0 = np.array([1, 2, 3, 4])
#eps = sys.float_info.epsilon
eps = 1e-6

In [9]:
print(hess(f, x0))
print(grad(f, x0))

[[ 1.20010668e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.00035560e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00008890e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00008890e+00  1.77635684e-03]]
[ 4.000006 -8.000002  4.        3.      ]


In [10]:
check_optimality(grad(f, x0), hess(f, x0))

False