In [2]:
import numpy as np
import util_aa as util

El archivo util_aa(util Análisis aplicado) tiene las funciones de la tarea 1. Primero defino la función de Rosenbrock tomada de wikipedia, tiene 2 parámetros, (a,b) el mínimo de la función se encuentra en (a,a^2). Nótese que  el Dominio es R2.

In [45]:
def rosenbrock(x, a = 1, b = 100):
    # x pertenece a R2
    return (a - x[0])**2 + b*(x[1] - x[0]**2)**2;


Ahora hacemmos el algoritmo 3.1 del nocedal

In [46]:
def backtracking_line_search(f, xk, p, c = .001, ro = .5):
    alpha = 1;
    f_k = f(xk)
    gr = util.gradiente(f,xk)
    while(f(xk + alpha*p) > f_k + c*alpha*gr.dot(p)):
        alpha*= ro;
    return alpha

La siguiente función será útil para el método de line search de Newton. Lo que hace es forzar que los eigenvalores de la 
hessiana sean positivos, es decir, la hace positiva definida. Lo hace sumándole una identidad multiplicada por un escalar
que crece exponencialmente base 2. Por lo tanto, la complejidad de este algoritmo es log base dos de n. Donde n es el eigenvalor
más grande en valor absoluto. Éste método fue sugerido por el profesor Miguel Ángel en una asesoría después de clase.

def make_pos_def(H):
    n = H.shape[0];
    Id = np.identity(n)
    t = .0001;
    while(not util.is_pos_def(H)):
        H = H + t*Id
        t *= 2
    return H

Ahora sí, haciendo uso de las dos funciones anteriores, el siguiente metodo es el line search de Newton. Algoritmo 3.2 del Nocedal

In [60]:
def line_search_newton(f, x, n=1000):
    eps = 0.0001
    n = 1000
    for i in range(n):
        B = make_pos_def(util.hessiana(f,x))
        gr = util.gradiente(f,x)
        p = np.linalg.solve(B, -1*gr)
        
        alpha = backtracking_line_search(f,x,p)
        x += alpha*p
    return x

Ahora las probaré con dos puntos iniciales elegidos arbitrariamente, pero sin ninguna felonía.

In [71]:
x1 = np.array([22.0,4.0])
x2 = np.array([4.0,.5])

Vamos a probar el algoritmo con la función de Rosenbrock, con 1000 iteraciones. Sabemos que el minimo global es
(a, a^2), en este caso es (1,1)

In [72]:
line_search_newton(rosenbrock,x1)

array([0.99780986, 0.99511786])

Se acerca mucho, tal y como queríamos, veamos con más iteraciones

In [73]:
line_search_newton(rosenbrock,x1,100000)

array([0.99780986, 0.99511786])

No está cambiando, por lo tanto podemos concluir que el error no se debe al número de iteraciones, si no a la epsilon definida en casi todos los métodos. Lógicamente haciendola más chica el resultado mejorará. Sin embargo, el tiempo de procesamiento aumentará. Por el momento el resultado me parece relativamente bueno, lo dejaré así.

Ahora probamos con el otro punto. Para asegurarnos que el algoritmo funciona.

In [74]:
line_search_newton(rosenbrock,x2)

array([0.98990489, 0.97985641])

Probaré con (a,b) = (2,100), debería de converger a (2,4)

In [66]:
def rosenbrock(x, a = 2, b = 100):
    # x pertenece a R2
    return (a - x[0])**2 + b*(x[1] - x[0]**2)**2;

In [67]:
line_search_newton(rosenbrock,x1)

array([1.95717723, 3.82771995])

Otra vez vemos muy buenos resultados, tal y como esperabamos. Por último probaré con (a,b) = (1,35) igual debería converger a (1,1)

In [68]:
def rosenbrock(x1, a = 1, b = 35):
    # x pertenece a R2
    return (a - x[0])**2 + b*(x[1] - x[0]**2)**2;

In [69]:
line_search_newton(rosenbrock,x1)

array([0.99203601, 0.98349739])

Ésta vez los resultados son aún mejores que la vez pasada. 