In [1]:
import numpy as np

pos nos dice cuál derivada parcial queremos calcular, 0 <=pos <= xk.size

In [72]:
def derivada_parcial(f, xk, pos):
    eps= 0.0001
    n = xk.size
    h = np.zeros(n)
    h[pos]+=eps
    return (f(xk + h) - f(xk))/eps

In [ ]:
el gradiente es las n derivadas parciales ordenadas de xk

In [7]:
def gradiente(f,xk):
    n = xk.size
    res = np.zeros(n)
    for i in range(n):
        res[i] = derivadaParcial(f,xk,i)
    return res

pos1 es la derivada con la cuál se hace la primera derivada parcial, y pos2 le hace la segunda derivada a la función obtenida por la primera derivada

In [91]:
def segunda_derivada(f, xk, pos1, pos2):
    eps = 0.0001
    n = xk.size
    h = np.zeros(n)
    h[pos2] += eps
    def f_prima(x):
        return derivada_parcial(f,x,pos1)
    return derivada_parcial(f_prima,xk,pos2)

la hessiana es la matriz con la combinación de las derivadas parciales de segundo orden

In [151]:
def hessiana(f,xk):
    n = xk.size
    res = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            res[i][j] = segunda_derivada(f,xk,i,j)
    return np.matrix(res)

las condiciones de optimalidad dictan que el gradiente tiene que ser diferente al vector 0, y que la hessiana debe ser definida
positiva, es decir, todos los eigenvalores positivos

In [152]:
def condiciones_optimalidad(f,xk):
    if(np.any(gradiente(f,xk))):
        return np.all(np.linalg.eigvals(hessiana(f,xk) > 0))
    return False

El mk es para la región de confianza. p es una matriz que representa a un vector columna (nx1)

In [153]:
def mk(f, xk, p):
    pt= p.transpose()
    return f(xk) + pt.dot(gradiente(f,xk)) + .5*(pt.dot((hessiana(f,xk)).dot(p)))

Pruebo ahora con un ejemplo de f, tomado del libro para ver si los resultados son los esperados.

In [154]:
def f(x):
    return 10*(x[1]-x[0]**2)**2 + (1-x[0])**2
xk = np.array([0,1])

In [155]:
gradiente(f,xk)

array([-2.0019, 20.001 ])

De acuerdo con el libro el gradiente es [-2 20], por lo tanto, el resultado es satisfactorio.

In [156]:
hessiana(f,xk)

matrix([[-3.79999982e+01, -1.99964489e-03],
        [-1.99964489e-03,  1.99999999e+01]])

De acuerdo con el libro la hessiana es [-38 0; 0 20], por lo tanto el resultado se acerca bastante al correcto.

In [157]:
condiciones_optimalidad(f,xk)

False

In [158]:
p = np.matrix([.5,.5]).transpose()
mk(f,xk,p)

matrix([[17.7490503]])