In [5]:
import numpy as np

In [1]:

def check_optimality(grad,hess):#grad R^n, hess Rnxn, np.array
    

SyntaxError: unexpected EOF while parsing (<ipython-input-1-3e456cf95123>, line 1)

In [27]:
def grad(f, x0): #x0 in R^n, np.array. f a function
    n=x0.size
    eps=0.0000001
    res=np.zeros(n)
    for i in range(n):
        aux=np.zeros(n)
        aux[i] +=eps
        xi=x0+aux
        res[i]=(f(xi)-f(x0))/eps
    return res

In [38]:
def hess(f, x0): #x0 in R^n, np.array
    n=x0.size
    eps=0.0000000001
    hes=np.zeros((n,n))
    grad0=grad(f,x0)
    for i in range(n):
        aux=np.zeros(n)
        aux[i] +=eps
        xi=x0+aux
        gradi= grad(f,xi)
        hes[:,i]=(gradi-grad0)/eps
    return hes

In [3]:
def f(x0):
    return np.sqrt(sum(x0**2))

In [21]:
def f(x0):
    return sum(x0**2+2*x0-3)
x0=np.array([2,5,4,3])
f(x0)

70

In [23]:
x0

array([2, 5, 4, 3])

In [28]:
grad(f,x0)

array([ 6.00000007, 12.00000014, 10.00000012,  8.00000009])

In [40]:
hess(f,x0)

array([[2.84217094, 0.        , 0.        , 0.        ],
       [0.        , 1.42108547, 0.        , 0.        ],
       [0.        , 0.        , 2.84217094, 0.        ],
       [0.        , 0.        , 0.        , 1.42108547]])