In [2]:
import numpy as np

In [3]:
x = 5
type(x)

int

In [4]:
lst = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

In [5]:
type(lst)

list

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
2:5

SyntaxError: illegal target for annotation (<ipython-input-8-0d10dca0029b>, line 1)

In [9]:
lst = [2:3]

SyntaxError: invalid syntax (<ipython-input-9-e60b12f07d16>, line 1)

In [10]:
lst[2:3]

[3]

In [11]:
arr[2:3]

array([3])

In [12]:
lst[-1] = "Las listas pueden tener varios tipos de datos"

In [13]:
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr[-1] = 1.2345
arr

array([1, 2, 3, 4, 1])

In [17]:
vec = np.arange(15)

In [18]:
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
vec = arange(15)
vec

NameError: name 'arange' is not defined

In [20]:
vec = np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [21]:
vec = np.array([1,2,3])
type(vec)

numpy.ndarray

In [22]:
vec2 = np.arange(3)
type(vec2)

numpy.ndarray

In [23]:
lst = arr.tolist

In [24]:
lst

<function ndarray.tolist>

In [25]:
print(lst)

<built-in method tolist of numpy.ndarray object at 0x7f4360189ad0>


In [26]:
alist = [4,6,2,3,6]
enumerate(alist)

In [27]:
x = enumerate(alist)

In [28]:
x

In [29]:
print(x)

In [30]:
type(x)

enumerate

In [31]:
for i in enumerate(alist):
    print(i)

(0, 4)
(1, 6)
(2, 2)
(3, 3)
(4, 6)


In [34]:
lista = [1,2,3,5,8,13,21]
def lst_multiplicacion(lista,escalar):
    for i , val in enumerate(lista):
        lista[i] = val
    return lista            

In [35]:
resp = lst_multiplicacion(lista,9)

In [36]:
resp

[1, 2, 3, 5, 8, 13, 21]

In [37]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [40]:
arr2d = np.zeros(5)
arr2d

array([0., 0., 0., 0., 0.])

In [41]:
arr2d = np.zeros((5,5))
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
arr2d = np.zeros((5,2))
arr2d

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
cubo = np.zeros((5,5,5))
cubo

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
cubo = np.zeros((5,5,5)).astype(int)+1
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [46]:
cubo = np.ones((5,5,5)).astype(np.float16)
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [47]:
cubo.dtype

dtype('float16')

In [48]:
np.empty((2,3))

array([[4.67991215e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [49]:
matrix = np.ones((3,3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
matrix[1]

array([1., 1., 1.])

In [52]:
matrix[1][2]

1.0

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(3)

array([0.30560837, 0.31207501, 0.20871679])

In [55]:
np.eye(4) + np.ones((4,4))

array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.]])

In [56]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr = np.arange(1000)
arr3d = arr.reshape((10,10,10))

In [60]:
arr3d.ndim

3

In [61]:
arr3d.shape

(10, 10, 10)

In [62]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [63]:
arr2d = arr.reshape((10,20))

ValueError: cannot reshape array of size 1000 into shape (10,20)

In [64]:
arr2d = arr.reshape((10,100))

In [65]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 17

In [66]:
arr = np.zeros((4,4,4,4))

In [67]:
arr.shape

(4, 4, 4, 4)

In [68]:
arr_plano = arr.ravel()
arr_plano.shape

(256,)

In [69]:
arr = np.arange(10)

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr_slice = arr[5:8]

In [72]:
arr_slice

array([5, 6, 7])

In [73]:
arr_slice[1] = 1234567

In [74]:
arr_slice

array([      5, 1234567,       7])

In [75]:
arr

array([      0,       1,       2,       3,       4,       5, 1234567,
             7,       8,       9])

In [1]:
arr = np.arange(9)
arr

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [5]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr.shape = (3,3)

In [9]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [11]:
arr[0:1]

array([[0, 1, 2]])

In [12]:
arr[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
arr[0:2][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [14]:
arr[1][2]

5

In [15]:
arr[:1,:2]

array([[0, 1]])

In [16]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
index = arr > 2

In [18]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
arr[index]

array([3, 4, 5, 6, 7, 8])

In [20]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr = np.ones((5,4))

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr[2]

array([1., 1., 1., 1.])

In [24]:
for i in range(5):
    arr[i] = i

In [30]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

## Funciones Universales

Las funciones universales realizan operaciones elemento por elemento en los arreglos.

In [31]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr = -1*arr

In [33]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [34]:
arr = np.random.rand(10)
arr

array([0.24335154, 0.21270203, 0.93694411, 0.68325979, 0.3374905 ,
       0.848992  , 0.33629233, 0.88524628, 0.23292785, 0.92167282])

In [35]:
arr = np.random.rand(2,2)

In [36]:
arr

array([[0.85732531, 0.45595263],
       [0.2219173 , 0.41921073]])

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr.sum()

45

In [42]:
arr = np.arange(10)
arr = arr.reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
arr = np.random.rand(5,4)
arr

array([[0.19028791, 0.8871316 , 0.83431315, 0.44483026],
       [0.32342579, 0.90205276, 0.25885499, 0.70517977],
       [0.1471526 , 0.83479947, 0.57283534, 0.84364847],
       [0.26387247, 0.849089  , 0.54059535, 0.75951449],
       [0.61179601, 0.1087659 , 0.42303795, 0.94142932]])

In [45]:
arr.sum()

11.442612589538504

In [46]:
arr.sum(0)

array([1.53653477, 3.58183873, 2.62963678, 3.6946023 ])

In [47]:
arr.sum(1)

array([2.35656292, 2.18951331, 2.39843587, 2.4130713 , 2.08502919])

In [49]:
arr = np.arange(10)
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

## Operaciones de conjuntos

In [55]:
arr = np.arange(10)
arr2 = np.arange(10) + 5
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
np.unique(arr2)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.intersect1d(arr,arr2)

array([5, 6, 7, 8, 9])

In [59]:
np.iinfo(np.int32).max, 2**31 - 1

(2147483647, 2147483647)

In [60]:
np.float64

numpy.float64

In [61]:
np.finfo(np.float64).max

1.7976931348623157e+308

## Estructuras de Datos

In [62]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [63]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [64]:
muestra.ndim

1

In [65]:
muestra.shape

(6,)

In [66]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

## Broadcasting (Segunda Vuelta)

In [67]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [68]:
x +3

array([3, 4, 5, 6])

In [69]:
a = np.arange(12).reshape((3,4))
print(a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
b = np.array([1,2,3])
print(b.shape)
b

(3,)


array([1, 2, 3])

In [71]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [72]:
b = b[:, np.newaxis]
print(b.shape)
b

(3, 1)


array([[1],
       [2],
       [3]])

In [73]:
a+b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [74]:
x = np.zeros((3,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
y = np.zeros(8)
y

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
x[...,None]

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [77]:
z = (x[...,None]+y)
print(z.shape)
z

(3, 5, 8)


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])