In [5]:
import numpy as np



In [6]:
def gradiente(f, xk):
    n=xk.size
    epsilon=10e-5
    fh = np.zeros(n)
    x_0 = np.array(xk)
    x_h = np.array(xk)
    for i in range(n):
        x_h[i] += epsilon
        fh[i] = (f(x_h)-f(x_0))/epsilon
        x_h[i] -= epsilon
    return fh

In [7]:
def hessiana(f, xk):
    n = xk.size
    epsilon = 10e-5
    h = np.zeros([n,n])
    for i in range(n):
        x_h = np.array(xk)
        x_h[i] += epsilon
        gx0 = np.array(gradiente(f,xk), dtype=float)
        gxh = np.array(gradiente(f,x_h), dtype=float)
        h[:,i] = (gxh - gx0)/epsilon
    return h


In [10]:
def condiciones_optimalidad(f, xk):
    if np.all(np.linalg.eigvals(hessiana(f,xk)) > 0) and np.all(gradiente(f,xk) == 0):
        return True
    else:
        return False
        

In [15]:
def mk(f, xk, p):
    h = hessiana(f, xk)
    grad = gradiente(f, xk).T
    return f(xk) + np.dot(p.T,grad) + 0.5*(np.dot(np.dot(p.T,h),p))


In [16]:
#EJEMPLO:
def f(xk):
    return 2*xk[0]**2 - 3*xk[1]**3 + 4*xk[2]**4;
xk = np.array([-1,0,1], dtype=float)
print(gradiente(f,xk))
print(hessiana(f,xk))
p = np.array([1,2,3],dtype=float).T
print(condiciones_optimalidad(f,xk))
print(mk(f,xk,p))


[-3.99980000e+00 -3.00026670e-08  1.60024002e+01]
[[ 3.99999998e+00  8.88178420e-08  0.00000000e+00]
 [ 8.88178420e-08 -1.79998239e-03  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.80096007e+01]]
False
268.04700354814923
