In [2]:
    import numpy as np
    print(np.__version__)

1.19.2


In [182]:
# Primero hagamos una función (que es la que meteremos en el gradiente)
def func1(x):
    y = x[0]**2 + x[0]*x[1] + 3*x[2]**2
    return y

In [296]:
def gradiente(func,xk):
    # Código que calcula el gradiente de la función f en el punto xk
    cambio = .000001
    n = len(xk)
    grad = np.zeros(n)
    
    for i in range(1,n+1):
        aux = xk.copy()
        aux[i-1] = aux[i-1] + cambio
        grad[i-1] = round((func(aux) - func(xk))/cambio,2)
    
    return np.matrix(grad)

In [252]:
xk = np.array([1.0,1.0,1.0])
gradiente(func1,xk)

array([3., 1., 6.])

In [314]:
def hessiana(func,xk):
    # Código que calcula la hessiana de la función f en el punto xk
    cambio = .000001
    n = len(xk)
    hess = np.zeros((n,n))
    
    for i in range(1,n+1):
        for j in range(1,n+1):
            if i==j:
                aux1 = xk.copy()
                aux2 = xk.copy()
                aux1[i-1] = aux1[i-1] + cambio
                aux2[i-1] = aux2[i-1] - cambio
                hess[i-1,j-1] = round((func(aux1)-2*func(xk)+func(aux2))/cambio**2,2)
            else:
                aux1 = xk.copy()
                aux2 = xk.copy()
                aux3 = xk.copy()
                
                aux1[i-1] = aux1[i-1] + cambio
                aux1[j-1] = aux1[j-1] + cambio
                
                aux2[j-1] = aux2[j-1] + cambio
                
                aux3[i-1] = aux3[i-1] + cambio
                
                hess[i-1,j-1] = round((func(aux1)-func(aux2)-func(aux3)+func(xk))/cambio**2,2)
                
    return np.matrix(hess)

In [215]:
xk = np.array([1.0,1.0,1.0])
hessiana(func1,xk)
np.zeros(3)

array([0., 0., 0.])

In [237]:
def condiciones_optimalidad(f,xk):
    # Función que determina si cierto punto en la función cumple
    # con las condiciones de optimalidad:
    # 1. Gradiente 0
    # 2. Hessiana semidefinida positiva
    
    n = len(xk)
    
    if all(gradiente(f,xk) == 0):
        r = "cumple gradiente 0"
    else:
        r = "no cumple gradiente 0"
    
    # Ahora checaremos si todos los eigenvalores son positivos
    # lo cual significa que es semidefinida positiva
    eigen = np.linalg.eig(hessiana(f,xk))[0]
    if all(eigen > 0):
        r = r, "cumple hessiana semidefinida positiva"
    else:
        r = r, "no cumple hessiana semidefinida positiva"
    
    return r

In [321]:
def mk(f,xk):
    cambio = .000001
    n = len(xk)
    p = np.matrix(np.zeros((n,1)) + cambio)
    mk = f(xk) + np.transpose(p)*np.transpose(gradiente(f,xk)) + .5*(np.transpose(p)*hessiana(f,xk))*p
    return np.array(mk)

In [322]:
xk = np.array([1.0,1.0,1.0])
mk(func1,xk)

array([[5.00001]])