In [1]:
import numpy as np

In [2]:
#Calcula el gradiente de una funcion f en el punto x0

#f es una funcion
#x0 es el punto donde se va a evaluar la funcion

def gradiente(f, x0):  
    n = x0.size
    grad = np.zeros(n)
    epsilon = 1e-7
    
    for i in range(n):
        t = np.zeros(n)
        t[i] = epsilon 
        x1 = x0 + t
        
        grad[i] = (f(x1) - f(x0)) / epsilon
        
    return grad

In [3]:
#Calcula la Hessiana de una funcion en el punto x0

#f es una funcion
#x0 es el punto donde se va a evaluar la funcion

def hessiana(f, x0):
    n = x0.size
    hess = np.zeros((n,n))
    epsilon = 1e-7
    
    for i in range(n):
        for j in range(n):
            
            ti = np.zeros(n)
            ti[i] = ti[i] + epsilon
            tj = np.zeros(n)
            tj[j] = tj[j] + epsilon
            
            x1 = x0 + ti + tj
            x2 = x0 + ti
            x3 = x0 + tj
            
            hess[i,j] = (f(x1) - f(x2) - f(x3) + f(x0)) / (epsilon ** 2)
            
    return hess

In [4]:
#La funcion dice si un punto cumple con ser un minimo local
#Regresa True si es minimo y False si no lo es

#f es una funcion
#x0 es el punto donde se va a evaluar la funcion

def condiciones_optimalidad(f, x0): 
    
    n = x0.size
    grad = gradiente(f, x0)
    hess = hessiana(f, x0)
    epsilon = 1e-5
    
    landa = np.linalg.eigvals(hess) #Valores propios
    resp = 0
    
    for i in range(n):
        if (-epsilon <= grad[i] <= epsilon) and (landa[i] >= 0):
            resp = resp + 1
            
    if resp == n:
        return True
    else:
        return False 

In [5]:
#Genera la funcion de aproximacion mk para el algoritmo de region de confianza

#f es una funcion
#x0 es el punto donde se va a evaluar la funcion

#Se tomara como direccion la de maximo descenso, es decir P = -gradiente

def mk(f, x0):
    
    grad = gradiente(f, x0)
    hess = hessiana(f,x0)
    P = -grad / np.linalg.norm(grad)
    
    return f(x0) + P.T.dot(grad) + 0.5 * (P.T.dot(hess)).dot(P)


##### Ejemplos

In [6]:
def f(x):
    return sum(x ** 2)

x1 = np.array([1,1,1])
x2 = np.array([0,0,0])

In [7]:
#Ejemplo con f(x1), x1 no es minimo

print('Valor de la funcion: ', f(x1))
print('\nGradiente: \n', gradiente(f,x1))
print('\nHessiana: \n', hessiana(f,x1))
print('\nEs punto minimo:\n ', condiciones_optimalidad(f, x1))
print('\nFuncion mk:\n ', mk(f, x1))

Valor de la funcion:  3

Gradiente: 
 [2.0000001 2.0000001 2.0000001]

Hessiana: 
 [[ 1.95399252 -0.04440892  0.        ]
 [-0.04440892  1.95399252  0.        ]
 [ 0.          0.          1.95399252]]

Es punto minimo:
  False

Funcion mk:
  0.49809149393557184


In [8]:
#Ejemplo con f(x2), x1 es minimo

print('Valor de la funcion: ', f(x2))
print('\nGradiente: \n', gradiente(f,x2))
print('\nHessiana: \n', hessiana(f,x2))
print('\nEs punto minimo:\n ', condiciones_optimalidad(f, x2))
print('\nFuncion mk:\n ', mk(f, x2))

Valor de la funcion:  0

Gradiente: 
 [1.e-07 1.e-07 1.e-07]

Hessiana: 
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

Es punto minimo:
  True

Funcion mk:
  0.9999998267949193


In [9]:
def f(x):
    return sum(x ** 2 + 2 * x - 5)

x = np.array([4,2,5,2])

In [10]:
print('Valor de la funcion: ', f(x))
print('\nGradiente: \n', gradiente(f,x))
print('\nHessiana: \n', hessiana(f,x))
print('\nEs punto minimo:\n ', condiciones_optimalidad(f, x))
print('\nFuncion mk:\n ', mk(f, x))

Valor de la funcion:  55

Gradiente: 
 [10.00000012  6.00000007 12.00000014  6.00000007]

Hessiana: 
 [[2.13162821 0.         0.         0.        ]
 [0.         2.84217094 0.         0.        ]
 [0.         0.         1.42108547 0.        ]
 [0.         0.         0.         2.84217094]]

Es punto minimo:
  False

Funcion mk:
  38.20847715466678
