# Proyecto Parte 1

### Integrantes del equipo:
 #### - Alejandro Chávez Mier 173199
 #### - Héctor Alejandro Vela Toriz 149427
 #### - Manuel García Garduño 162136
 #### - Karla Susana Alva Ortiz 174144

In [1]:
import numpy as np

##### Gradiente

In [2]:
def grad(f, x0):
    
    n = x0.size
    eps = 0.00001
    res = np.zeros(n)
    
    for i in range(n):
        aux = np.zeros(n)
        aux[i] = eps
        x1 = x0 + aux
        res[i] = (f(x1) - f(x0)) / eps   
        
    return res

##### Hessiana

In [3]:
def hess(f,x0):
    
    n = x0.size
    eps = 0.00001
    res = np.zeros((n,n))
    
    for i in range(n):
        
        aux = np.zeros(n)
        aux[i] = eps
        x1 = x0 + aux
        res[:,i] = (grad(f,x1) - grad(f,x0)) / eps
        
    return res

### Algoritmo 3.1: Para encontrar a $\alpha$

In [4]:
def alfa(f,x0,p):
    
    ro = 0.8
    c = 0.0001
    alpha = 1
    
    while f(x0 + alpha * p) > f(x0) + c * alpha * (grad(f,x0).T).dot(p):
        
        alpha = ro * alpha
        
    return alpha

### Algoritmo 3.3: Para encontrar a $\gamma$

In [5]:
def calcula_gamma(A):
    
    k = 100
    n = A.shape[0]
    beta = 0.001
    
    diagonal = np.diagonal(A)
    minimo = np.amin(diagonal)
    
    if minimo > 0:
        gamma = 0
    else:
        gamma = -minimo + beta
    #end if
    
    for i in range(k):    
        
        try:
            np.linalg.cholesky(A + gamma * np.identity(n))
        except np.linalg.LinAlgError:
            gamma = max([2 * gamma, beta])
        else:
            break
            
    return gamma

### Algoritmo 3.2: Método de Newton con modificación a la Hessiana

In [6]:
def newton_mod(f,x0):
    
    k = 1000
    n = x0.size
    
    for i in range(k):
        
        gamma = calcula_gamma(hess(f, x0))
        B0 = hess(f, x0) + gamma * np.identity(n)
        
        p0 = -np.linalg.inv(B0).dot(grad(f,x0))        
        alpha = alfa(f, x0, p0)
        
        x0 = x0 + alpha * p0
        
        #para ver si la función realmente decrece
        #print(f(x0)) 
        
    return x0

###  Función de Rosenbrock

In [7]:
def rosenbrock(x0):
    
    a = 1
    b = 100
    
    return (a - x0[0]) ** 2 + b * (x0[1] - x0[0] ** 2) ** 2

### Pruebas

###### El mínimo de la función de Rosenbrock se encuentra en $(a, a^2)$. 
###### Para las siguientes pruebas se utiliza a = 1 y b = 100, por lo que el resultado que obtengamos debe de estar cercano a (1,1)

In [8]:
x0 = np.array([1.5,1.5])

newton_mod(rosenbrock, x0)

array([0.99701189, 0.9940277 ])

In [9]:
x0 = np.array([2,-2])

newton_mod(rosenbrock, x0)

array([0.99975837, 0.99950485])

In [10]:
x0 = np.array([22,50])

newton_mod(rosenbrock, x0)

array([0.99769669, 0.99539032])

In [11]:
x0 = np.array([-0.5,0.8])

newton_mod(rosenbrock, x0)

array([0.99700991, 0.99402376])

##### Para las siguientes pruebas se definirá la función de Rosenbrock con a = 4 y b = 50, por lo que el mínimo se encuentra en (4, 16)

In [12]:
def rosenbrock(x0):
    
    a = 4
    b = 50
    
    return (a - x0[0]) ** 2 + b * (x0[1] - x0[0] ** 2) ** 2

In [13]:
x0 = np.array([4.5,50])

newton_mod(rosenbrock, x0)

array([ 3.98265548, 15.86153535])

In [14]:
x0 = np.array([22,50])

newton_mod(rosenbrock, x0)

array([ 3.98603482, 15.88843262])

In [15]:
x0 = np.array([3,5])

newton_mod(rosenbrock, x0)

array([ 3.98214639, 15.85748491])

In [16]:
x0 = np.array([-10,100])

newton_mod(rosenbrock, x0)

array([ 3.98214639, 15.85748491])