In [4]:
import numpy as np

In [5]:
#La funcion dice si un punto cumple con ser un minimo local
#Regresa True si es minimo y False si no lo es

def check_optimality(grad, hess): #grad R^n, hess Rnxn
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-5-be80315a4326>, line 5)

In [30]:
#Calcula el gradiente de una funcion en el punto x0
#x0 R^n, f una funcion

def grad(f, x0):  
    n = x0.size
    gradiente = np.zeros(n)
    epsilon = 0.00000001
    
    for i in range(n):
        t = np.zeros(n)
        t[i] = epsilon 
        gradiente[i] = (f(t + x0) - f(x0)) / epsilon
        
    return gradiente

In [31]:
def f(x0):
    return sum(x0 ** 2 + 2 * x0 - 5)
x0 = np.array([4,2,5,2])
f(x0)

55

In [32]:
grad(f,x0)

array([10.00000012,  5.99999979, 12.00000028,  5.99999979])

In [79]:
#Calcula la Hessiana de una funcion en el punto x0
#x0 R^n, f una funcion
def hess(f, x0):
    n = x0.size
    hessiana = np.zeros((n,n))
    epsilon = 0.00000001
    gradiente1 = grad(f, x0) #Son las primeras derivadas
    
    for i in range(n):
        t = np.zeros(n)
        t[i] = epsilon 
        gradiente2 = grad(f, (x0 + t))
        hessiana[:,i] = (gradiente2 - gradiente1) / epsilon
        
        return hessiana

In [80]:
def f(x0):
    return x0[1] ** 4 + x0[0] ** 3 + 3 * x0[0] ** 2 + 4 * x0[1] ** 2 - 4 * x0[0] * x0[1] - 5 * x0[1] + 8
x0 = np.array([1,0])
f(x0)

12

In [81]:
def f(x0):
    return x0[0] ** 2 + x0[1] ** 2
x0 = np.array([1,0])
f(x0)

1

In [82]:
grad(f,x0)

array([1.99999999, 0.        ])

In [83]:
hess(f, x0)

array([[4.4408921, 0.       ],
       [0.       , 0.       ]])

In [8]:
#Funcion de prueba, el minimo esta en el vector 0
#Se supone que la funcion existe en el punto
def f(x0):
    return np.sqrt(sum(x0**2))