In [1]:
import numpy as np

In [2]:
#La funcion dice si un punto cumple con ser un minimo local
#Regresa True si es minimo y False si no lo es

def check_optimality(grad, hess): #grad R^n, hess Rnxn
    n = grad.size
    landa = np.linalg.eigvals(hess) #Valores propios
    resp = False
    
    for i in range(n):
        if (grad[i] == 0) and (landa[i] >= 0):
            resp = True
            
    return resp
    

In [3]:
#Calcula el gradiente de una funcion en el punto x0
#x0 R^n, f una funcion

def grad(f, x0):  
    n = x0.size
    gradiente = np.zeros(n)
    epsilon = 0.00000001
    
    for i in range(n):
        t = np.zeros(n)
        t[i] = epsilon 
        gradiente[i] = (f(t + x0) - f(x0)) / epsilon
        
    return gradiente

In [4]:
def f(x0):
    return sum(x0 ** 2 + 2 * x0 - 5)
x0 = np.array([4,2,5,2])
f(x0)

55

In [5]:
grad(f,x0)

array([10.00000012,  5.99999979, 12.00000028,  5.99999979])

In [15]:
#Calcula la Hessiana de una funcion en el punto x0
#x0 R^n, f una funcion
def hess(f, x0):
    n = x0.size
    hessiana = np.zeros((n,n))
    epsilon = 0.00000001
    gradiente1 = grad(f, x0) #Son las primeras derivadas
    
    for i in range(n):
        t = np.zeros(n)
        t[i] = epsilon 
        gradiente2 = grad(f, (x0 + t))
        hessiana[:,i] = (gradiente2 - gradiente1) / epsilon
        
        return hessiana

In [7]:
def f(x0):
    return x0[1] ** 4 + x0[0] ** 3 + 3 * x0[0] ** 2 + 4 * x0[1] ** 2 - 4 * x0[0] * x0[1] - 5 * x0[1] + 8
x0 = np.array([1,0])
f(x0)

12

In [8]:
def f(x0):
    return x0[0] ** 2 + x0[1] ** 2
x0 = np.array([1,0])
f(x0)

1

In [9]:
grad(f,x0)

array([1.99999999, 0.        ])

In [10]:
hess(f, x0)

array([[4.4408921, 0.       ],
       [0.       , 0.       ]])

In [11]:
#Funcion de prueba, el minimo esta en el vector 0
#Se supone que la funcion existe en el punto
def f(x0):
    return np.sqrt(sum(x0**2))

In [12]:
def f(x):
    return 10 * (x[1] - x[0] ** 2) ** 2 + (1 - x[0]) ** 2
x = np.array([0,1])
f(x)

11

In [13]:
grad(f,x)

array([-2.00000017, 19.99999988])

In [16]:
hess(f,x)

array([[ 53.29070518,   0.        ],
       [-17.76356839,   0.        ]])