**Tarea 1: Condiciones de optimalidad**\
Tonantzin Real Rojas \
**C.U.** 163491 \
**Fecha:** Septiembre 17, 2020

In [67]:
import numpy as np
from numpy import linalg as LA

In [114]:
# Función con la que probamos

def f(x0):
    return sum(x0**2 + 2*x0 -5)
    #return sum(x0**2)

x0 = np.array([4,2,5,2])
#x0 = np.array([0,0,0,0])
print(f(x0))

print(gradiente(f,x0))

A = [[1, 4, 5],
    [-5, 8, 9],
    [2,3,4]]

#A = [[0, 0, 0],
#    [0, 0, 0],
#    [0,0,0]]

v,w= LA.eig(A)
print(v)

print(hessiana(f,x0))

55
[10.000001  6.000001 12.000001  6.000001]
[ 0.07690488  2.49349439 10.42960073]
[1.99662509 2.00373051 1.99662509 2.00373051]


In [12]:
# Código que calcula el gradiente de la función f en el punto xk

def gradiente(f, xk):  # xk in R^n, np.array, f a function
    n = xk.size
    epsilon = 0.000001
    res = np.zeros(n)
    
    for i in range(n):
        zer = np.zeros(n)
        zer[i] += epsilon
        x1 = xk + zer
        res[i] = (f(x1) - f(xk))/epsilon
    return res

In [16]:
# Código que calcula la hessiana

def hessiana(f, xk): # xk in R^n, np.array
    n = xk.size
    epsilon = 0.000001
    res = np.zeros(n)
    
    for i in range(n):
        zer = np.zeros(n)
        zer[i] += epsilon
        xS = xk + zer     # x + h
        xR = xk - zer     # x - h
        res[i] = (f(xS) - 2*f(xk) + f(xR)) / (epsilon**2)    # Diferencia finita centrada
    return res

In [115]:
# Código que regresa si el punto xk cumple con las condiciones de optimalidad

def condiciones_optimalidad(gradiente,hessiana):
    n = gradiente.size
    flagG = True
    
    # Gradiente = 0
    for i in range(n):
        if gradiente[i] != 0:    # Entradas del gradiente deben ser 0 para la optimalidad
            flagG = False
    
    if flagG == False:
        print("El gradiente no es distinto de cero")
    
    # Hessiana definida positiva
    v, w = LA.eig(A)   # Sacamos los eigenpares
    vLen = v.size
    flagH = True
    
    for i in range(vLen):
        if v[i] <= 0:
            flagH = False
    
    if flagH == False:
        print("La  hessiana no es positiva definida")
    
    # Las condiciones de optimalidad se cumplen
    if flagG == True and flagH == True:
        print("Las condiciones de optimalidad se cumplen")

In [113]:
condiciones_optimalidad(gradiente(f,x0),A)

El gradiente no es distinto de cero


In [ ]:
# Código que genera la función de aproximación mk que vimos en clase para el algoritmo de región de confianza
def mk(f,xk):